"""Council of Thought — core protocol.

Pure logic: seats, sessions, prompts, decision records. No network, no MCP,
no credentials. Importable and testable on its own.

Storage is plain files under COUNCIL_HOME (default ~/council). Deliberately
not a database: the decision records are meant to be read, edited and
committed to git by a human.
"""
from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional


# --------------------------------------------------------------------- seats

@dataclass(frozen=True)
class Seat:
    key: str
    name: str
    mandate: str
    default_provider: str


SEATS: tuple[Seat, ...] = (
    Seat(
        "steelman", "The Steelman",
        "Build the strongest possible version of this idea. Assume it worked — "
        "describe what had to be true for that to happen.",
        "openai",
    ),
    Seat(
        "red_team", "The Red Team",
        "Assume this failed twelve months from now. Write the post-mortem. "
        "Name the specific mechanism of death, not a generic risk.",
        "anthropic",
    ),
    Seat(
        "evidence", "The Evidence",
        "What is verifiably true right now? Who has already tried this? "
        "Cite sources with URLs and dates, or state plainly 'no evidence found'.",
        "gemini",
    ),
    Seat(
        "numbers", "The Numbers",
        "Model this. Cost to reach the first dollar, break-even volume, and "
        "what the founder is not counting.",
        "anthropic",
    ),
    Seat(
        "operator", "The Operator",
        "Can this actually be built in 1-2 hours a day on this budget? List "
        "every step required. If the list is long, say so plainly.",
        "ollama",
    ),
)

SEATS_BY_KEY = {s.key: s for s in SEATS}


def seat(key: str) -> Seat:
    try:
        return SEATS_BY_KEY[key]
    except KeyError:
        raise ValueError(
            f"Unknown seat {key!r}. Valid seats: {', '.join(SEATS_BY_KEY)}"
        ) from None


# ------------------------------------------------------------------- storage

def council_home() -> Path:
    return Path(os.environ.get("COUNCIL_HOME", Path.home() / "council")).expanduser()


def _sessions_dir() -> Path:
    return council_home() / "sessions"


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _slug(text: str, limit: int = 40) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return (s[:limit].rstrip("-")) or "decision"


def _session_path(session_id: str) -> Path:
    # session_id is generated by us, but never trust it as a path component.
    if "/" in session_id or "\\" in session_id or session_id.startswith("."):
        raise ValueError(f"Invalid session id: {session_id!r}")
    return _sessions_dir() / session_id / "session.json"


def _read(session_id: str) -> dict[str, Any]:
    p = _session_path(session_id)
    if not p.exists():
        raise ValueError(f"No council session {session_id!r}. Run convene_council first.")
    return json.loads(p.read_text(encoding="utf-8"))


def _write(session: dict[str, Any]) -> None:
    p = _session_path(session["id"])
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(session, indent=2), encoding="utf-8")


# -------------------------------------------------------------------- thesis

CONTEXT_BLOCK = """\
Solo operator. 1-2 hours per day. Tight budget that grows with revenue.
Stack: Claude, Gemini, ChatGPT, Ollama (local, free), Blotato, Hermes.
Channels: TikTok, YouTube, Instagram. US primary, UK/CA/AU secondary.
Phase-one goal: affiliate and brand-deal revenue.
Existing asset: owned contact databases (cold/purchased, ~500-5,000)."""


def convene(
    *,
    decision: str,
    belief: str,
    reasoning: str,
    cost_dollars: float,
    cost_hours: float,
    expected_return: str,
    refutation: str,
    reversible: bool,
    context: str = CONTEXT_BLOCK,
) -> dict[str, Any]:
    """Open a council session. Returns the session with all five seat prompts."""
    if not decision.strip():
        raise ValueError("decision must not be empty — state an action, not a topic.")
    if not refutation.strip():
        raise ValueError(
            "refutation must not be empty. An idea with no refutation condition "
            "is a preference, not a thesis, and the council cannot test it."
        )

    ts = datetime.now(timezone.utc)
    session_id = f"{ts.strftime('%Y%m%d-%H%M%S')}-{_slug(decision)}"
    thesis = {
        "decision": decision.strip(),
        "belief": belief.strip(),
        "reasoning": reasoning.strip(),
        "cost_dollars": cost_dollars,
        "cost_hours": cost_hours,
        "expected_return": expected_return.strip(),
        "refutation": refutation.strip(),
        "reversible": bool(reversible),
    }
    session = {
        "id": session_id,
        "opened_at": _now(),
        "thesis": thesis,
        "context": context,
        "responses": {},
        "decision_record": None,
    }
    _write(session)
    return session


def thesis_block(session: dict[str, Any]) -> str:
    t = session["thesis"]
    return (
        f"Decision on the table:      {t['decision']}\n"
        f"What I believe:             {t['belief']}\n"
        f"Why I believe it:           {t['reasoning']}\n"
        f"What it costs:              ${t['cost_dollars']:,.0f} and {t['cost_hours']:g} hours\n"
        f"What I expect in return:    {t['expected_return']}\n"
        f"How I will know I'm wrong:  {t['refutation']}\n"
        f"Reversible?                 {'Yes' if t['reversible'] else 'No'}"
    )


def seat_prompt(session: dict[str, Any], seat_key: str) -> str:
    s = seat(seat_key)
    return f"""\
You are Seat: {s.name} on a five-seat decision council.
You are NOT a general assistant and you are NOT here to be balanced.
Your entire job is to argue your mandate as forcefully as the evidence allows.
Another seat covers the opposite view. Do not do their job.

MY MANDATE: {s.mandate}

FOUNDER THESIS:
{thesis_block(session)}

CONTEXT:
{session['context']}

RETURN EXACTLY THIS, NOTHING ELSE:
1. POSITION        - your verdict in one sentence.
2. THREE ARGUMENTS - strongest first, each with its supporting reason.
3. THE ONE THING   - the single most important thing the founder is getting
                     wrong or missing, from your seat's angle.
4. CONFIDENCE      - High / Medium / Low, and what would move it.
5. IF I AM WRONG   - the strongest argument against your own position.

Be specific. Name tools, numbers and dates. A generic answer is a failed answer.
Never present as fact anything you have not actually retrieved this run. If you
cannot verify something, write UNVERIFIED."""


def all_seat_prompts(session: dict[str, Any]) -> dict[str, str]:
    return {s.key: seat_prompt(session, s.key) for s in SEATS}


def record_response(
    session_id: str, seat_key: str, response: str, *, model: str = "unknown"
) -> dict[str, Any]:
    seat(seat_key)  # validate
    if not response.strip():
        raise ValueError("response must not be empty.")
    session = _read(session_id)
    session["responses"][seat_key] = {
        "seat": seat_key,
        "model": model,
        "recorded_at": _now(),
        "response": response.strip(),
    }
    _write(session)
    return session


CHAIR_COUNSEL = """\
Act as Chair's counsel on these council responses.

1. Where do the seats genuinely DISAGREE? Quote the conflicting claims directly.
   Ignore differences that are only wording — name real conflicts.
2. Where do they AGREE? Flag any agreement that looks like a shared assumption
   rather than shared evidence. That is the dangerous kind.
3. Which single claim, if false, would break the most other claims? Name that
   load-bearing assumption and give one way to test it this week for under $50.
4. What did NO seat raise that should have been raised?
5. Give three options — PROCEED, PROCEED MODIFIED, or KILL — each with the
   specific condition that should trigger it.

Do not tell me what to do. Tell me what I am deciding between."""


def cross_examination(session_id: str) -> str:
    session = _read(session_id)
    got = session["responses"]
    if not got:
        raise ValueError(
            "No seat responses recorded yet. Record at least two before "
            "cross-examination — one opinion is not a council."
        )
    parts = [f"FOUNDER THESIS:\n{thesis_block(session)}", ""]
    for s in SEATS:
        r = got.get(s.key)
        if r:
            parts.append(f"=== {s.name} ({r['model']}) ===\n{r['response']}\n")
        else:
            parts.append(f"=== {s.name} === [NO RESPONSE RECORDED]\n")
    missing = [s.name for s in SEATS if s.key not in got]
    if missing:
        parts.append(
            f"NOTE: {len(missing)} seat(s) did not respond: {', '.join(missing)}. "
            "Weigh the synthesis accordingly — do not treat silence as agreement.\n"
        )
    parts.append(CHAIR_COUNSEL)
    return "\n".join(parts)


def record_decision(
    session_id: str,
    *,
    decision: str,
    chose: str,
    overruled_seat: str,
    load_bearing_bet: str,
    kill_trigger: str,
    review_date: str,
) -> dict[str, Any]:
    valid = {"PROCEED", "MODIFIED", "KILL"}
    d = decision.strip().upper()
    if d not in valid:
        raise ValueError(f"decision must be one of {sorted(valid)}, got {decision!r}")
    session = _read(session_id)
    n = len(list(_sessions_dir().glob("*/DECISION-*.md"))) + 1
    record = {
        "number": n,
        "decided_at": _now(),
        "decision": d,
        "chose": chose.strip(),
        "overruled_seat": overruled_seat.strip(),
        "load_bearing_bet": load_bearing_bet.strip(),
        "kill_trigger": kill_trigger.strip(),
        "review_date": review_date.strip(),
    }
    session["decision_record"] = record
    _write(session)

    md = f"""# Decision Record #{n}

**Decided:** {record['decided_at']}
**Session:** `{session_id}`

| Field | Value |
|---|---|
| Decision | **{d}** |
| What I chose | {record['chose']} |
| Overruled seat | {record['overruled_seat']} |
| Load-bearing bet | {record['load_bearing_bet']} |
| Kill trigger | {record['kill_trigger']} |
| Review date | {record['review_date']} |

## Thesis

```
{thesis_block(session)}
```

## Seats heard

{chr(10).join(f'- {seat(k).name} ({v["model"]})' for k, v in session['responses'].items()) or '- none'}

## At review — fill this in on {record['review_date']}

- **What happened:**
- **Who was right:**
- **What I now do differently:**
"""
    out = _session_path(session_id).parent / f"DECISION-{n:03d}.md"
    out.write_text(md, encoding="utf-8")
    return {"record": record, "path": str(out)}


def list_sessions() -> list[dict[str, Any]]:
    d = _sessions_dir()
    if not d.exists():
        return []
    rows = []
    for sess in sorted(d.iterdir(), reverse=True):
        f = sess / "session.json"
        if not f.exists():
            continue
        try:
            s = json.loads(f.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        rec = s.get("decision_record")
        rows.append({
            "id": s["id"],
            "opened_at": s.get("opened_at"),
            "decision": s["thesis"]["decision"],
            "seats_heard": len(s.get("responses", {})),
            "outcome": rec["decision"] if rec else "OPEN",
            "review_date": rec["review_date"] if rec else None,
        })
    return rows
